### ISSUE TITLE
Not working with nextjs 9

### ISSUE THREAD

**Issue by krish-dev** [rohanray/next-fonts#21]
This plugin is not working with the current version of Nextjs (9).
Not able to add font face with SCSS

**Comment by ChrisDalley** [comment]
Also having this issue, seems to be with the change from using `/static` to `/public` to locate static assets such as fonts and images.

**Comment by LuigiDerson** [comment]
> 
> 
> Also having this issue, seems to be with the change from using `/static` to `/public` to locate static assets such as fonts and images.

Yep, It seems like /static is deprecated, so I think we need to modify it to be /public instead

**Comment by rohanray** [comment]
@krish-dev @ChrisDalley @LuigiDerson : Thanks for reporting! I have just published v. 1.0.1 where in I have replaced static with public. Please let me know if that works. Regards -RR

**Comment by LuigiDerson** [comment]
> 
> 
> @krish-dev @ChrisDalley @LuigiDerson : Thanks for reporting! I have just published v. 1.0.1 where in I have replaced static with public. Please let me know if that works. Regards -RR

I'm still getting the error, it is working fine with static although. Im getting this erros in the browser console, I'm using Styled Components and I followed the steps to make them work.
![issue](https://user-images.githubusercontent.com/47396669/72512229-91e6ae80-3843-11ea-86bb-dfe5a1ea5750.png)

**Comment by igl** [comment]
Current version is broken. The asset that are compiled by next still need to end up in static.
`public` is only for your non-compiled static files from the file system.

![image](https://user-images.githubusercontent.com/293519/72522983-1dba0400-385f-11ea-971f-5a5fa97ce20e.png)

**Comment by nbdn** [comment]
Same thing, I think this commit must be reversed: https://github.com/rohanray/next-fonts/commit/8ea9d92cdeecb069224fbfb0f9842a80c029bcee

**Comment by rohanray** [comment]
Reverted https://github.com/rohanray/next-fonts/commit/8ea9d92cdeecb069224fbfb0f9842a80c029bcee.

Published new version 1.0.2

**Comment by rohanray** [comment]
Please see https://github.com/rohanray/next-fonts-example for usage with Nextjs v9.2+

This should work with next-fonts v1.0.2

**Comment by rohanray** [comment]
> Please see https://github.com/rohanray/next-fonts-example for usage with Nextjs v9.2+
> 
> This should work with next-fonts v1.0.2

@krish-dev Please test next-fonts v1.0.2 and let me know if we can close this issue.

**Comment by Valentino-Houessou** [comment]
> > Please see https://github.com/rohanray/next-fonts-example for usage with Nextjs v9.2+
> > This should work with next-fonts v1.0.2
> 
> @krish-dev Please test next-fonts v1.0.2 and let me know if we can close this issue.

@rohanray I test next-fonts v1.0.3 and the issue is solved. But it doesn't work when coupled with styled-component. I've followed [font-error](https://github.com/rohanray/font-error). But the issue persists.

**Comment by Valentino-Houessou** [comment]
> > > Please see https://github.com/rohanray/next-fonts-example for usage with Nextjs v9.2+
> > > This should work with next-fonts v1.0.2
> > 
> > 
> > @krish-dev Please test next-fonts v1.0.2 and let me know if we can close this issue.
> 
> @rohanray I test next-fonts v1.0.3 and the issue is solved. But it doesn't work when coupled with styled-component. I've followed [font-error](https://github.com/rohanray/font-error). But the issue persists.

I fixed it by updating the _app.js to add the globalStyle. And it's working fine. Thanks @rohanray

**Comment by rohanray** [comment]
@Valentino-Houessou : Thanks much for confirming back! I would really appreciate if you can submit a PR at https://github.com/rohanray/next-fonts-example with a basic running set-up of next-fonts & styled-component

**Comment by Valentino-Houessou** [comment]
> @Valentino-Houessou : Thanks much for confirming back! I would really appreciate if you can submit a PR at https://github.com/rohanray/next-fonts-example with a basic running set-up of next-fonts & styled-component

I've just made it. Thanks.

**Comment by rohanray** [comment]
> > @Valentino-Houessou : Thanks much for confirming back! I would really appreciate if you can submit a PR at https://github.com/rohanray/next-fonts-example with a basic running set-up of next-fonts & styled-component
> 
> I've just made it. Thanks.

@Valentino-Houessou : Sorry but I don't see a PR https://github.com/rohanray/next-fonts-example/pulls. Please let me know if you need any help. Thanks -RR

**Comment by Valentino-Houessou** [comment]
> > > @Valentino-Houessou : Thanks much for confirming back! I would really appreciate if you can submit a PR at https://github.com/rohanray/next-fonts-example with a basic running set-up of next-fonts & styled-component
> > 
> > 
> > I've just made it. Thanks.
> 
> @Valentino-Houessou : Sorry but I don't see a PR https://github.com/rohanray/next-fonts-example/pulls. Please let me know if you need any help. Thanks -RR

oh sorry @rohanray, i did it on https://github.com/rohanray/font-error/pulls instead, I've just done it on https://github.com/rohanray/next-fonts-example/pulls also.

**Comment by rohanray** [comment]
> > > > @Valentino-Houessou : Thanks much for confirming back! I would really appreciate if you can submit a PR at https://github.com/rohanray/next-fonts-example with a basic running set-up of next-fonts & styled-component
> > > 
> > > 
> > > I've just made it. Thanks.
> > 
> > 
> > @Valentino-Houessou : Sorry but I don't see a PR https://github.com/rohanray/next-fonts-example/pulls. Please let me know if you need any help. Thanks -RR
> 
> oh sorry @rohanray, i did it on https://github.com/rohanray/font-error/pulls instead, I've just done it on https://github.com/rohanray/next-fonts-example/pulls also.

@Valentino-Houessou : Merged your PR! Thanks much for the contribution. Cheers -Rohan
